server:
  port: 80

spring:
  mail:
    host: smtp.qq.com
    username: 1299461580@qq.com
    password: gfwhbdocanmzbaag
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
